"""add_tags_to_cost_data

Revision ID: c3440fc1c128
Revises: d4751abf99ef
Create Date: 2025-11-13 13:38:57.268927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3440fc1c128'
down_revision = 'd4751abf99ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_data', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_data', 'tags')
    # ### end Alembic commands ###
