"""add_budgets_and_alerts

Revision ID: 20512331ba1a
Revises: 04329139c8dd
Create Date: 2025-11-14 20:59:35.735005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20512331ba1a'
down_revision = '04329139c8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', name='budgetperiod'), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('custom_webhook_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['aws_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_account_id'), 'budgets', ['account_id'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('percentage_used', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('notification_channels_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_account_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
