"""Add Stripe fields to Tenant

Revision ID: 094c8a33f26b
Revises: 263c62cf898f
Create Date: 2025-11-19 09:30:30.877912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094c8a33f26b'
down_revision = '263c62cf898f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cloud_accounts_provider', table_name='cloud_accounts')
    op.drop_index('ix_cloud_accounts_tenant_id', table_name='cloud_accounts')
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'subscription_plan')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'stripe_customer_id')
    op.create_index('ix_cloud_accounts_tenant_id', 'cloud_accounts', ['tenant_id'], unique=False)
    op.create_index('ix_cloud_accounts_provider', 'cloud_accounts', ['provider'], unique=False)
    # ### end Alembic commands ###
