"""Add cost data tables

Revision ID: d4751abf99ef
Revises: 001
Create Date: 2025-11-13 12:35:57.677523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4751abf99ef'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('aws_account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('usage_type', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_account_date', 'cost_data', ['aws_account_id', 'date'], unique=False)
    op.create_index('idx_cost_date', 'cost_data', ['date'], unique=False)
    op.create_index('idx_cost_service', 'cost_data', ['service'], unique=False)
    op.create_index('idx_cost_tenant_date', 'cost_data', ['tenant_id', 'date'], unique=False)
    op.create_table('cost_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('aws_account_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_account_period', 'cost_summaries', ['aws_account_id', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_summary_tenant_period', 'cost_summaries', ['tenant_id', 'period_start', 'period_end'], unique=False)
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'])
    op.drop_index('idx_summary_tenant_period', table_name='cost_summaries')
    op.drop_index('idx_summary_account_period', table_name='cost_summaries')
    op.drop_table('cost_summaries')
    op.drop_index('idx_cost_tenant_date', table_name='cost_data')
    op.drop_index('idx_cost_service', table_name='cost_data')
    op.drop_index('idx_cost_date', table_name='cost_data')
    op.drop_index('idx_cost_account_date', table_name='cost_data')
    op.drop_table('cost_data')
    # ### end Alembic commands ###
